// Generated by CoffeeScript 1.6.3
var PaperclipViewDecorator, paperclip, type,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

paperclip = require("paperclip");

type = require("type-component");

PaperclipViewDecorator = (function() {
  /*
  */

  function PaperclipViewDecorator(view) {
    this.view = view;
    this.dispose = __bind(this.dispose, this);
    this.render = __bind(this.render, this);
    this._onTemplateChange = __bind(this._onTemplateChange, this);
    this.view.once("render", this.render);
    this.view.once("dispose", this.dispose);
    this.view.bind("paper").to(this._onTemplateChange).now();
  }

  /*
  */


  PaperclipViewDecorator.prototype._onTemplateChange = function(template) {
    if (type(template) !== "function") {
      throw new Error("paper template must be a function for view \"" + this.view.constructor.name + "\"");
    }
    this.template = paperclip.template(template, this.view.application);
    if (this._rendered) {
      this.dispose();
      return this.render();
    }
  };

  /*
  */


  PaperclipViewDecorator.prototype.render = function() {
    this.dispose();
    this._rendered = true;
    if (!this.template) {
      return;
    }
    return this.view.section.append((this.content = this.template.bind(this.view)).toFragment());
  };

  /*
  */


  PaperclipViewDecorator.prototype.dispose = function() {
    if (!this.content) {
      return;
    }
    return this.content.dispose();
  };

  /*
  */


  PaperclipViewDecorator.getOptions = function(view) {
    return view.__isView;
  };

  PaperclipViewDecorator.decorate = function(view, options) {
    return new PaperclipViewDecorator(view, options);
  };

  return PaperclipViewDecorator;

})();

module.exports = function(app) {
  return app.decorator(module.exports.decorator);
};

module.exports.decorator = {
  priority: "render",
  decorator: PaperclipViewDecorator,
  inheritable: false
};
